name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get kwok
        run: wget -O kwokctl -c "https://github.com/kubernetes-sigs/kwok/releases/download/v0.1.1/kwokctl-$(go env GOOS)-$(go env GOARCH)"

      - name: fix kwok
        run: chmod +x kwokctl && mv kwokctl /usr/local/bin/kwokctl

      - name: test helm success 1.24.12
        run: make --no-print-directory test-success-1.24.12

      - name: test helm failure 1.25.8
        run: make --no-print-directory test-failure-1.25.8

      - name: test kubectl server-side 1.24.12
        run: make --no-print-directory test-kubectl-1.24.12

      - name: test kubectl server-side 1.25.8
        run: make --no-print-directory test-kubectl-1.25.8
