name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get kwok
        run: wget -O kwokctl -c "https://github.com/kubernetes-sigs/kwok/releases/download/v0.1.1/kwokctl-$(go env GOOS)-$(go env GOARCH)"

      - name: kwok
        run: chmod +x kwokctl

      - name: kwok
        run: mv kwokctl /usr/local/bin/kwokctl

      - name: config
        run: make test
